import { NgModule } from "@angular/core";
import { MatTableModule, 
    MatNativeDateModule, 
    MatIconModule, 
    MatSidenavModule, 
    MatAutocompleteModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatInputModule,
    MatButtonToggleModule,
    MatListModule,
    MatDatepickerModule,
    MatTabsModule,
    MatDialogModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatMenuModule } from '@angular/material';


@NgModule({
    imports: [
        MatTableModule, 
        MatNativeDateModule, 
        MatIconModule, 
        MatSidenavModule, 
        MatAutocompleteModule,
        MatButtonModule,
        MatCardModule,
        MatCheckboxModule,
        MatInputModule,
        MatButtonToggleModule,
        MatListModule,
        MatDatepickerModule,
        MatTabsModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatSnackBarModule,
        MatMenuModule ],
    exports: [
        MatTableModule, 
        MatNativeDateModule, 
        MatIconModule, 
        MatSidenavModule, 
        MatAutocompleteModule,
        MatButtonModule,
        MatCardModule,
        MatCheckboxModule,
        MatInputModule,
        MatButtonToggleModule,
        MatListModule,
        MatDatepickerModule,
        MatTabsModule,
        MatDialogModule,
        MatProgressSpinnerModule,
        MatSnackBarModule,
        MatMenuModule ]
  })
  export class MaterialModule { }
  